---
  - name: Provision MySql on AWS
    hosts: localhost
    connection: local
    tasks:
    - name: Creating MYSQL database on AWS
      community.aws.rds:
        command: create
        instance_name: mfadin-mysql
        db_engine: MySQL
        size: 10
        instance_type: db.t2.micro
        username: mysql_admin
        password: 1nsecure
        tags:
          Environment: testing
          Application: cms
