---
  - name: Provision MySql on AWS
    hosts: all
    remote_user: ubuntu
    tasks:
    - name: install ansible galaxy
      command: ansible-galaxy collection install community.aws    
    - name: echo env values
      shell: export AWS_REGION=us-east-2
    - name: Creating MYSQL database on AWS
      community.aws.rds:
        command: create
        instance_name: mfadin-mysql
        db_engine: MySQL
        size: 10
        instance_type: db.t2.micro
        username: mysql_admin
        password: 1nsecure
        region: us-east-2
        tags:
          Environment: testing
          Application: cms
